In [55]:
import pandas as pd
import geopandas
cross_lochs = pd.read_csv('../cross_lochs_gdf_pft.csv')

# cross_lochs_focused = cross_lochs[cross_lochs.columns[360:364]]

cross_lochs.head()

,Unnamed: 0,band1,band2,band3,band4,band5,band6,band7,band8,band9,...,band354,band355,band356,band357,band358,POINTID,geometry,GRID_CODE,PFT,line
0,0,0.001099,0.003430,0.004752,0.006146,0.006639,0.009240,0.010558,0.011710,0.013801,...,0.072792,0.075150,0.074088,0.074698,0.072248,1,POINT (444724.307637 6472605.65507),0.001099,calluna_mix,1
1,1,0.003365,0.002541,0.004668,0.006236,0.006519,0.008654,0.010603,0.012083,0.012975,...,0.070987,0.072956,0.070970,0.067680,0.067113,2,POINT (444729.307637 6472605.65507),0.003365,calluna_mix,1
2,2,0.002603,0.002340,0.005392,0.006031,0.006805,0.008977,0.010990,0.012230,0.014469,...,0.086899,0.087825,0.089891,0.086141,0.085678,3,POINT (444734.307637 6472605.65507),0.002603,calluna_mix,1
3,3,0.002381,0.004279,0.005815,0.006092,0.007620,0.009825,0.012374,0.014953,0.016326,...,0.101852,0.101284,0.103357,0.100732,0.099883,4,POINT (444739.307637 6472605.65507),0.002381,calluna_mix,1
4,4,0.002342,0.002837,0.005055,0.005912,0.006696,0.009762,0.010999,0.012902,0.015368,...,0.094130,0.091242,0.095368,0.093193,0.093215,5,POINT (444744.307637 6472605.65507),0.002342,calluna_mix,1

In [57]:
from sklearn.cluster import KMeans

# kmeans = KMeans(n_clusters=5, random_state=0).fit(cross_lochs_gdf[1:359])

kmeans = KMeans(n_clusters=5)

x = cross_lochs[cross_lochs.columns[1:359]]

y = kmeans.fit_predict(x)

y_df = pd. DataFrame(y, columns=['Cluster'])

cross_lochs['Cluster'] = y_df

print(cross_lochs.head())

   Unnamed: 0     band1     band2     band3     band4     band5     band6  \
0           0  0.001099  0.003430  0.004752  0.006146  0.006639  0.009240
1           1  0.003365  0.002541  0.004668  0.006236  0.006519  0.008654
2           2  0.002603  0.002340  0.005392  0.006031  0.006805  0.008977
3           3  0.002381  0.004279  0.005815  0.006092  0.007620  0.009825
4           4  0.002342  0.002837  0.005055  0.005912  0.006696  0.009762

      band7     band8     band9  ...   band355   band356   band357   band358  \
0  0.010558  0.011710  0.013801  ...  0.075150  0.074088  0.074698  0.072248
1  0.010603  0.012083  0.012975  ...  0.072956  0.070970  0.067680  0.067113
2  0.010990  0.012230  0.014469  ...  0.087825  0.089891  0.086141  0.085678
3  0.012374  0.014953  0.016326  ...  0.101284  0.103357  0.100732  0.099883
4  0.010999  0.012902  0.015368  ...  0.091242  0.095368  0.093193  0.093215

   POINTID                             geometry  GRID_CODE          PFT  line  \
0        1  POINT (444724.307637 6472605.65507)   0.001099  calluna_mix     1
1        2  POINT (444729.307637 6472605.65507)   0.003365  calluna_mix     1
2        3  POINT (444734.307637 6472605.65507)   0.002603  calluna_mix     1
3        4  POINT (444739.307637 6472605.65507)   0.002381  calluna_mix     1
4        5  POINT (444744.307637 6472605.65507)   0.002342  calluna_mix     1

   Cluster
0        2
1        2
2        2
3        2
4        2

[5 rows x 365 columns]

In [58]:
y_df.describe()

            Cluster
count  42021.000000
mean       2.130054
std        1.311341
min        0.000000
25%        1.000000
50%        3.000000
75%        3.000000
max        4.000000

In [60]:
cross_lochs['geometry'] = geopandas.GeoSeries.from_wkt(cross_lochs['geometry'])

cross_lochs_gdf = geopandas.GeoDataFrame(cross_lochs, geometry='geometry')

# cross_lochs_gdf.head(2)

# cross_lochs_focused = cross_lochs[cross_lochs_gdf.columns[360:365]]

cross_lochs_gdf.head()

# gdf.head()

,Unnamed: 0,band1,band2,band3,band4,band5,band6,band7,band8,band9,...,band355,band356,band357,band358,POINTID,geometry,GRID_CODE,PFT,line,Cluster
0,0,0.001099,0.003430,0.004752,0.006146,0.006639,0.009240,0.010558,0.011710,0.013801,...,0.075150,0.074088,0.074698,0.072248,1,POINT (444724.308 6472605.655),0.001099,calluna_mix,1,2
1,1,0.003365,0.002541,0.004668,0.006236,0.006519,0.008654,0.010603,0.012083,0.012975,...,0.072956,0.070970,0.067680,0.067113,2,POINT (444729.308 6472605.655),0.003365,calluna_mix,1,2
2,2,0.002603,0.002340,0.005392,0.006031,0.006805,0.008977,0.010990,0.012230,0.014469,...,0.087825,0.089891,0.086141,0.085678,3,POINT (444734.308 6472605.655),0.002603,calluna_mix,1,2
3,3,0.002381,0.004279,0.005815,0.006092,0.007620,0.009825,0.012374,0.014953,0.016326,...,0.101284,0.103357,0.100732,0.099883,4,POINT (444739.308 6472605.655),0.002381,calluna_mix,1,2
4,4,0.002342,0.002837,0.005055,0.005912,0.006696,0.009762,0.010999,0.012902,0.015368,...,0.091242,0.095368,0.093193,0.093215,5,POINT (444744.308 6472605.655),0.002342,calluna_mix,1,2

In [61]:
cross_lochs_gdf.to_file("cross_lochs_kmc_alt.shp")

In [62]:
cross_lochs_gdf.to_csv("cross_lochs_kmc_alt.csv")

In [ ]:
# issue - tried to reduce the size of the shape file, but whenever I removed columns, it wouldn't recognise the geometry