In [1]:
import pandas as pd
import geopandas
cross_lochs = pd.read_csv('../cross_lochs_6_classes_for_ML.csv')
# cross_lochs = pd.read_csv('../transformed_spectral_signatures/second_derivative_98_sample.csv')
# cross_lochs = pd.read_csv('../transformed_spectral_signatures/BDNA_98_sample.csv')

cross_lochs['geometry'] = geopandas.GeoSeries.from_wkt(cross_lochs['geometry'])

cross_lochs_gdf = geopandas.GeoDataFrame(cross_lochs, geometry='geometry')

cross_lochs_gdf.head()

/home/rzw/.local/lib/python3.8/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

,Unnamed: 0,band1,band2,band3,band4,band5,band6,band7,band8,band9,...,band353,band354,band355,band356,band357,band358,POINTID,geometry,GRID_CODE,PFT
0,412,0.003409,0.003283,0.004620,0.006938,0.007003,0.009061,0.011035,0.013070,0.016138,...,0.090197,0.088069,0.092271,0.089105,0.089418,0.091109,413,POINT (444754.308 6472595.655),0.003409,calluna_mix
1,413,0.002237,0.005423,0.006024,0.006861,0.007332,0.010247,0.012456,0.013884,0.017221,...,0.096534,0.098906,0.093759,0.099614,0.096711,0.096978,414,POINT (444759.308 6472595.655),0.002237,calluna_mix
2,617,0.000951,0.005150,0.005988,0.006720,0.007361,0.010606,0.012082,0.014234,0.015797,...,0.096551,0.097626,0.096350,0.095506,0.098056,0.096859,618,POINT (444764.308 6472590.655),0.000951,calluna_mix
3,821,0.002823,0.002804,0.005312,0.006705,0.007482,0.009891,0.012163,0.013613,0.016889,...,0.097774,0.096034,0.095319,0.100638,0.097645,0.098486,822,POINT (444769.308 6472585.655),0.002823,calluna_mix
4,822,0.002991,0.004075,0.004819,0.005989,0.007388,0.009729,0.012035,0.013280,0.016029,...,0.089470,0.091884,0.090096,0.090060,0.089917,0.090350,823,POINT (444774.308 6472585.655),0.002991,calluna_mix

In [2]:
from sklearn.model_selection import train_test_split


train_shrub_sphagnum, test_shrub_sphagnum = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('shrub_sphagnum')], test_size=0.4)
train_water, test_water = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('water')], test_size=0.4)
train_sphagnum_r, test_sphagnum_r = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('spahgnum_r')], test_size=0.4)
train_pool_bogbean, test_pool_bogbean = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('pool_bogbean')], test_size=0.4)
train_calluna_mix, test_calluna_mix = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('calluna_mix')], test_size=0.4)
train_rushes_sedges, test_rushes_sedges = train_test_split(cross_lochs_gdf[cross_lochs_gdf['PFT'].str.contains('rushes_sedges')], test_size=0.4)


train_frames = [train_shrub_sphagnum, train_water, train_sphagnum_r, train_pool_bogbean, train_calluna_mix, train_rushes_sedges]
test_frames = [test_shrub_sphagnum, test_water, test_sphagnum_r, test_pool_bogbean, test_calluna_mix, test_rushes_sedges]


train = pd.concat(train_frames)
test = pd.concat(test_frames)


train.head()

,Unnamed: 0,band1,band2,band3,band4,band5,band6,band7,band8,band9,...,band353,band354,band355,band356,band357,band358,POINTID,geometry,GRID_CODE,PFT
362,32109,-0.000246,0.001300,0.002716,0.002508,0.004115,0.006769,0.008662,0.010700,0.012611,...,0.084835,0.084283,0.085410,0.087434,0.085477,0.084107,32110,POINT (444899.308 6471815.655),-0.000246,shrub_sphagnum
345,25090,0.000918,0.002523,0.004647,0.006099,0.007176,0.009703,0.013067,0.014400,0.016614,...,0.085068,0.082973,0.086864,0.087186,0.085234,0.087427,25091,POINT (445329.308 6471990.655),0.000918,shrub_sphagnum
337,22636,0.001147,0.002200,0.003967,0.004440,0.005794,0.008394,0.009741,0.011311,0.013530,...,0.069174,0.068015,0.065944,0.067941,0.066479,0.065856,22637,POINT (445239.308 6472050.655),0.001147,shrub_sphagnum
384,38689,-0.000072,0.001673,0.003904,0.005279,0.006468,0.009267,0.011505,0.013499,0.015724,...,0.100356,0.100258,0.100698,0.101976,0.102319,0.100021,38690,POINT (445319.308 6471655.655),-0.000072,shrub_sphagnum
317,12253,0.002089,0.002377,0.003900,0.004572,0.004394,0.006844,0.008359,0.009351,0.010874,...,0.041992,0.041804,0.038927,0.041973,0.039326,0.040567,12254,POINT (445089.308 6472305.655),0.002089,shrub_sphagnum

In [3]:
# initial dataset

x_train = train[train.columns[1:359]]
y_train = train[train.columns[362]]

x_test = test[test.columns[1:359]]
y_test = test[test.columns[362]]

x_test.head(2)


#derivatives dataset

# x_train = train[train.columns[1:359]]
# y_train = train[train.columns[359]]

# x_test = test[test.columns[1:359]]
# y_test = test[test.columns[359]]

# x_test.head(2)

,band1,band2,band3,band4,band5,band6,band7,band8,band9,band10,...,band349,band350,band351,band352,band353,band354,band355,band356,band357,band358
323,0.001409,0.002337,0.004544,0.005835,0.007631,0.010704,0.012565,0.013781,0.01703,0.019987,...,0.109657,0.112433,0.109518,0.109911,0.110146,0.112403,0.111487,0.10897,0.110885,0.111866
297,0.000772,0.001622,0.003557,0.005556,0.005497,0.008465,0.010042,0.011418,0.01335,0.015071,...,0.081645,0.082329,0.079832,0.081359,0.082125,0.081856,0.080896,0.08437,0.079111,0.081770

In [4]:
from sklearn import dummy

dc = dummy.DummyClassifier()
dc.fit(x_train, y_train)
dc_score = dc.score(x_test, y_test)

print("Baseline Accuracy:", dc_score)

Baseline Accuracy: 0.16666666666666666

In [9]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt

svc = SVC(kernel='linear')
svc.fit(x_train, y_train)

y_pred = svc.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

scores = cross_val_score(svc, x_train, y_train, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

[[39  0  0  1  0  0]
 [ 1 21  0 16  0  2]
 [ 3  2  5  0 25  5]
 [10  6  0 23  0  1]
 [ 0  0  0  0 40  0]
 [ 5  1  0  3  0 31]]
                precision    recall  f1-score   support

   calluna_mix       0.67      0.97      0.80        40
  pool_bogbean       0.70      0.53      0.60        40
 rushes_sedges       1.00      0.12      0.22        40
shrub_sphagnum       0.53      0.57      0.55        40
    spahgnum_r       0.62      1.00      0.76        40
         water       0.79      0.78      0.78        40

      accuracy                           0.66       240
     macro avg       0.72      0.66      0.62       240
  weighted avg       0.72      0.66      0.62       240

0.64 accuracy with a standard deviation of 0.04

In [10]:
scores = cross_val_score(svc, x_test, y_test, cv=3)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

0.65 accuracy with a standard deviation of 0.03

In [11]:
# now want to predict for the whole dataset using the svc
cross_lochs = pd.read_csv('../cross_lochs_gdf.csv')

cross_lochs['geometry'] = geopandas.GeoSeries.from_wkt(cross_lochs['geometry'])

cross_lochs_gdf = geopandas.GeoDataFrame(cross_lochs, geometry='geometry')

cross_lochs_gdf

,Unnamed: 0,band1,band2,band3,band4,band5,band6,band7,band8,band9,...,band353,band354,band355,band356,band357,band358,POINTID,geometry,GRID_CODE,PFT
0,0,0.001099,0.003430,0.004752,0.006146,0.006639,0.009240,0.010558,0.011710,0.013801,...,0.074587,0.072792,0.075150,0.074088,0.074698,0.072248,1,POINT (444724.308 6472605.655),0.001099,NaN
1,1,0.003365,0.002541,0.004668,0.006236,0.006519,0.008654,0.010603,0.012083,0.012975,...,0.069210,0.070987,0.072956,0.070970,0.067680,0.067113,2,POINT (444729.308 6472605.655),0.003365,NaN
2,2,0.002603,0.002340,0.005392,0.006031,0.006805,0.008977,0.010990,0.012230,0.014469,...,0.086315,0.086899,0.087825,0.089891,0.086141,0.085678,3,POINT (444734.308 6472605.655),0.002603,NaN
3,3,0.002381,0.004279,0.005815,0.006092,0.007620,0.009825,0.012374,0.014953,0.016326,...,0.103626,0.101852,0.101284,0.103357,0.100732,0.099883,4,POINT (444739.308 6472605.655),0.002381,NaN
4,4,0.002342,0.002837,0.005055,0.005912,0.006696,0.009762,0.010999,0.012902,0.015368,...,0.093658,0.094130,0.091242,0.095368,0.093193,0.093215,5,POINT (444744.308 6472605.655),0.002342,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42016,42016,0.001845,0.002345,0.004714,0.005430,0.006393,0.008860,0.010772,0.012449,0.014887,...,0.077407,0.076553,0.078615,0.078627,0.078251,0.077265,42017,POINT (445714.308 6471575.655),0.001845,NaN
42017,42017,0.002455,0.002271,0.004029,0.005480,0.006396,0.008863,0.011025,0.012685,0.014688,...,0.073803,0.074018,0.074871,0.075158,0.073604,0.075263,42018,POINT (445719.308 6471575.655),0.002455,NaN
42018,42018,0.002387,0.002279,0.004424,0.005426,0.006352,0.008929,0.010853,0.012708,0.014964,...,0.082753,0.083324,0.083870,0.084588,0.081337,0.082178,42019,POINT (445724.308 6471575.655),0.002387,NaN
42019,42019,0.002777,0.002263,0.004564,0.005324,0.006339,0.008972,0.011173,0.012952,0.015367,...,0.094481,0.092089,0.094319,0.095786,0.090843,0.091052,42020,POINT (445729.308 6471575.655),0.002777,NaN
42020,42020,0.002096,0.002014,0.004155,0.005212,0.006220,0.008746,0.010900,0.012765,0.015355,...,0.094004,0.092630,0.094959,0.095417,0.094887,0.096628,42021,POINT (445734.308 6471575.655),0.002096,NaN

In [12]:
x = cross_lochs_gdf[cross_lochs_gdf.columns[1:359]]

x.head()

,band1,band2,band3,band4,band5,band6,band7,band8,band9,band10,...,band349,band350,band351,band352,band353,band354,band355,band356,band357,band358
0,0.001099,0.003430,0.004752,0.006146,0.006639,0.009240,0.010558,0.011710,0.013801,0.015441,...,0.077946,0.077413,0.077153,0.078934,0.074587,0.072792,0.075150,0.074088,0.074698,0.072248
1,0.003365,0.002541,0.004668,0.006236,0.006519,0.008654,0.010603,0.012083,0.012975,0.015468,...,0.075149,0.073557,0.071610,0.071727,0.069210,0.070987,0.072956,0.070970,0.067680,0.067113
2,0.002603,0.002340,0.005392,0.006031,0.006805,0.008977,0.010990,0.012230,0.014469,0.017382,...,0.088601,0.087386,0.087973,0.089698,0.086315,0.086899,0.087825,0.089891,0.086141,0.085678
3,0.002381,0.004279,0.005815,0.006092,0.007620,0.009825,0.012374,0.014953,0.016326,0.018532,...,0.105301,0.103799,0.104660,0.107808,0.103626,0.101852,0.101284,0.103357,0.100732,0.099883
4,0.002342,0.002837,0.005055,0.005912,0.006696,0.009762,0.010999,0.012902,0.015368,0.017144,...,0.095351,0.096855,0.094500,0.093532,0.093658,0.094130,0.091242,0.095368,0.093193,0.093215

In [13]:
clf_pred_full = svc.predict(x)

clf_pred_full

array(['spahgnum_r', 'spahgnum_r', 'calluna_mix', ..., 'calluna_mix',
       'calluna_mix', 'calluna_mix'], dtype=object)

In [14]:
# initial dataset

model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[360:362]]

# derivatives

# model_results_full = cross_lochs_gdf[cross_lochs_gdf.columns[359:361]]

model_results_full = model_results_full.assign(clf_pred_full = clf_pred_full)

model_results_full.head()

                         geometry  GRID_CODE clf_pred_full
0  POINT (444724.308 6472605.655)   0.001099    spahgnum_r
1  POINT (444729.308 6472605.655)   0.003365    spahgnum_r
2  POINT (444734.308 6472605.655)   0.002603   calluna_mix
3  POINT (444739.308 6472605.655)   0.002381   calluna_mix
4  POINT (444744.308 6472605.655)   0.002342   calluna_mix

In [15]:
model_results_full.to_file("cross_lochs_svc_98_sample_full_0.4_gdf.shp")

model_results_full.to_csv("cross_lochs_svc_98_sample_full_0.4_gdf.csv")

/tmp/ipykernel_7600/3504623746.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  model_results_full.to_file("cross_lochs_svc_98_sample_full_0.4_gdf.shp")